PRESET_TEMPLATES = [
    {
        'id':       'tiktok_clutch',
        'label':    'TikTok Clutch',
        'description': 'Highlights a single, high-energy gaming moment for maximum short-form impact.',
        'content_type_note': 'Short (<3min) gaming clip with intense action and clear audio from streamer.',
        'platforms': ['tiktok', 'youtube_shorts', 'instagram_reels'],
        'addOns': {
            'captions':   {'active': True, 'style': 'animated', 'position': 'center'},
            'audio':      {'loudnorm': True, 'duck': False},
            'branding':   {'active': True, 'brandId': 'ROB_BRAND_ID_PLACEHOLDER'},
            'colorGrade': {'active': True, 'preset': 'vivid'},
            'effects':    {'zoom': True, 'transitions': True, 'speed': True},
            'tts':        {'active': False},
            'contentType': 'clips',
        },
        'format': 'portrait',
        'expect_status': ('staged', 'complete'),
        'clip_selector': 'short',
        'rationale': 'Fast-paced visual effects and animated captions are crucial for engaging short-form audiences. Vivid color grading enhances the gaming experience. TTS is excluded as clips have original audio.'
    },
    {
        'id':       'youtube_deep_dive',
        'label':    'YouTube Deep Dive',
        'description': 'Comprehensive VOD review or educational content for YouTube, focusing on clarity and retention.',
        'content_type_note': 'Long-form VOD (>10min) of educational content, gameplay analysis, or a detailed discussion.',
        'platforms': ['youtube'],
        'addOns': {
            'captions':   {'active': True, 'style': 'clean', 'position': 'bottom'},
            'audio':      {'loudnorm': True, 'duck': True},
            'branding':   {'active': True, 'brandId': 'ROB_BRAND_ID_PLACEHOLDER'},
            'colorGrade': {'active': True, 'preset': 'neutral'},
            'effects':    {'zoom': False, 'transitions': True},
            'tts':        {'active': False},
            'contentType': 'educational',
        },
        'format': 'landscape',
        'expect_status': ('staged', 'complete', 'published'),
        'clip_selector': 'vod',
        'rationale': 'Clean captions aid comprehension for long-form content. Neutral color grade and minimal effects prioritize educational value. TTS is excluded as it is spoken content.'
    },
    {
        'id':       'irl_story_time',
        'label':    'IRL Story Time',
        'description': 'Shares a personal story or vlog from an IRL stream, adapted for multiple platforms.',
        'content_type_note': 'Medium-form VOD (5-15min) from an IRL stream, focusing on storytelling and streamer personality.',
        'platforms': ['tiktok', 'youtube_shorts', 'instagram_reels', 'youtube'],
        'addOns': {
            'captions':   {'active': True, 'style': 'clean', 'position': 'bottom'},
            'audio':      {'loudnorm': True, 'duck': True},
            'branding':   {'active': True, 'brandId': 'ROB_BRAND_ID_PLACEHOLDER'},
            'colorGrade': {'active': True, 'preset': 'warm'},
            'effects':    {'zoom': True, 'transitions': True},
            'tts':        {'active': False},
            'contentType': 'irl',
        },
        'format': 'portrait',
        'expect_status': ('staged', 'complete'),
        'clip_selector': 'vod',
        'rationale': 'Clean captions and warm color grade enhance storytelling. Zoom and transitions engage viewers. This template is designed for multi-platform output, generating both portrait and landscape versions optimized for each destination.'
    },
    {
        'id':       'montage_hype_reel',
        'label':    'Montage Hype Reel',
        'description': 'Combines multiple short, exciting clips into a high-energy highlight reel for social media.',
        'content_type_note': 'Multiple short (<1min) clips demonstrating a theme (e.g., best plays, funny moments).',
        'platforms': ['tiktok', 'youtube_shorts', 'instagram_reels'],
        'addOns': {
            'captions':   {'active': True, 'style': 'animated', 'position': 'center'},
            'audio':      {'loudnorm': True, 'duck': True},
            'branding':   {'active': True, 'brandId': 'ROB_BRAND_ID_PLACEHOLDER'},
            'colorGrade': {'active': True, 'preset': 'vivid'},
            'effects':    {'zoom': True, 'transitions': True, 'speed': True},
            'tts':        {'active': False},
            'contentType': 'montage',
        },
        'format': 'portrait',
        'expect_status': ('staged', 'complete'),
        'clip_selector': 'montage',
        'rationale': 'Animated captions and vivid grading amplify the excitement of rapid-fire clips. Aggressive use of effects (zoom, speed, transitions) maintains high energy. TTS is unnecessary with existing audio.'
    },
    {
        'id':       'reaction_rhapsody',
        'label':    'Reaction Rhapsody',
        'description': 'Showcases streamer's reactions to videos or events, tailored for engagement on YouTube.',
        'content_type_note': 'VOD segment (5-20min) of streamer reacting to external content with their commentary.',
        'platforms': ['youtube', 'twitter'],
        'addOns': {
            'captions':   {'active': True, 'style': 'clean', 'position': 'bottom'},
            'audio':      {'loudnorm': True, 'duck': True},
            'branding':   {'active': True, 'brandId': 'ROB_BRAND_ID_PLACEHOLDER'},
            'colorGrade': {'active': True, 'preset': 'neutral'},
            'effects':    {'zoom': True, 'transitions': True},
            'tts':        {'active': False},
            'contentType': 'reaction',
        },
        'format': 'landscape',
        'expect_status': ('staged', 'complete', 'published'),
        'clip_selector': 'vod',
        'rationale': 'Clean captions and clear audio are paramount for reaction content. Zoom effects highlight facial expressions. Optimized for YouTube's long-form and Twitter's easy sharing of video.'
    },
    {
        'id':       'quick_guide',
        'label':    'Quick Guide',
        'description': 'Concise educational or tutorial content, ideal for quick learning on social platforms.',
        'content_type_note': 'Short clip (1-5min) offering a quick tip, tutorial, or explanation.',
        'platforms': ['youtube_shorts', 'tiktok', 'instagram_reels'],
        'addOns': {
            'captions':   {'active': True, 'style': 'clean', 'position': 'center'},
            'audio':      {'loudnorm': True, 'duck': True},
            'branding':   {'active': True, 'brandId': 'ROB_BRAND_ID_PLACEHOLDER'},
            'colorGrade': {'active': True, 'preset': 'cool'},
            'effects':    {'zoom': True, 'transitions': True},
            'tts':        {'active': False},
            'contentType': 'educational',
        },
        'format': 'portrait',
        'expect_status': ('staged', 'complete'),
        'clip_selector': 'short',
        'rationale': 'Clean and centered captions ensure key information is easily digestible. Cool color grading provides a professional, calm feel suitable for tutorials. TTS is avoided when direct instruction is key.'
    }
]