#!/usr/bin/env python3
"""Fetch live job data and write it into the canvas data file.
Run: python3 scripts/refresh_canvas_jobs.py
"""
import os, sys, json, requests
from pathlib import Path

ROOT = Path(__file__).parent.parent
ENV  = dict(line.split("=", 1) for line in (ROOT / ".env").read_text().splitlines()
            if "=" in line and not line.startswith("#"))

KEY      = ENV.get("AURAFLUX_E2E_API_KEY_GUIDED", "")
API_BASE = "https://auraflux-api.onrender.com"
OUT      = Path.home() / ".cursor/projects/Users-robertgregory-cwn-production/canvases/canvas-job-data.ts"

def main():
    r = requests.get(f"{API_BASE}/v1/jobs?limit=50",
                     headers={"Authorization": f"Bearer {KEY}"}, timeout=20)
    r.raise_for_status()
    jobs = r.json().get("jobs", [])

    ts = f"// AUTO-GENERATED by scripts/refresh_canvas_jobs.py — {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}\nexport const JOBS = {json.dumps(jobs, indent=2)} as const;\n"
    OUT.write_text(ts)
    print(f"✅  Wrote {len(jobs)} jobs → {OUT}")

if __name__ == "__main__":
    main()
