'use strict';
/**
 * lib/gates/metadata_qa.js — CPD-1049
 * Semantic publish metadata checks before Gate 5 / platform upload.
 */

const DEFAULT_PROHIBITED = [
  'artificial intelligence',
  'chatgpt',
  ' ai ',
  'generated by ai',
  'ai-generated',
];

function _collectText(metadata = {}) {
  const parts = [
    metadata.title,
    metadata.description,
    metadata.caption,
    ...(metadata.tags || []),
  ].filter(Boolean);
  return parts.join(' ').toLowerCase();
}

function _clipTitles(jobSpec = {}) {
  const items = jobSpec.order?.inputs?.items || jobSpec.items || [];
  return items
    .map((it) => it.title || it.headline || it.clipTitle || it.displayName || '')
    .filter(Boolean);
}

/**
 * Validate publish metadata against job content.
 * @returns {{ passed: boolean, violations: string[] }}
 */
function validatePublishMetadata(jobSpec = {}, metadata = {}) {
  const violations = [];
  const title = String(metadata.title || '').trim();
  const description = String(metadata.description || metadata.caption || '').trim();
  const prohibited = [
    ...DEFAULT_PROHIBITED,
    ...(jobSpec.designSpec?.voice?.prohibitedWords || []),
  ].map((w) => String(w).toLowerCase()).filter(Boolean);

  if (!title) violations.push('title is required');

  const haystack = _collectText({ ...metadata, title, description });
  for (const word of prohibited) {
    const needle = word.trim();
    if (!needle) continue;
    if (haystack.includes(needle)) {
      violations.push(`prohibited term in metadata: "${needle.trim()}"`);
    }
  }

  const ct = String(jobSpec.contentType || '').toLowerCase();
  const isClipComp = ct.includes('short') || ct.includes('clip') || jobSpec.designSpec?.chrome?.layout === 'clip-comp';
  if (isClipComp && /\b(ai|artificial intelligence|chatgpt)\b/i.test(title)) {
    violations.push('clip comp title must not contain AI/ChatGPT marketing terms');
  }

  const clipTitles = _clipTitles(jobSpec);
  if (isClipComp && clipTitles.length > 0 && title) {
    const titleLower = title.toLowerCase();
    const anyMatch = clipTitles.some((t) => {
      const words = String(t).toLowerCase().split(/\s+/).filter((w) => w.length > 3);
      return words.some((w) => titleLower.includes(w));
    });
    if (!anyMatch) {
      violations.push('title does not reference any selected clip topic');
    }
  }

  // Short-form TikTok/IG caption limits are enforced in gate5.validatePrePublish.
  // YouTube Shorts descriptions are intentionally longer (hashtags + credits).

  return { passed: violations.length === 0, violations };
}

function reviewHoldEnabled() {
  return String(process.env.C0_REVIEW_HOLD ?? 'on').toLowerCase() !== 'off';
}

module.exports = { validatePublishMetadata, reviewHoldEnabled, DEFAULT_PROHIBITED };
