'use strict';
/**
 * lib/gates/metadata_qa.js — CPD-1049
 * Semantic publish metadata checks before Gate 5 / platform upload.
 */

const DEFAULT_PROHIBITED = [
  'artificial intelligence',
  'chatgpt',
  ' ai ',
  'generated by ai',
  'ai-generated',
];

function countWords(text) {
  return String(text || '').trim().split(/\s+/).filter(Boolean).length;
}

function countHashtagsInText(text) {
  return (String(text || '').match(/#\w+/g) || []).length;
}

function _hasProhibitedTerm(haystack, needle) {
  const n = String(needle || '').trim().toLowerCase();
  if (!n) return false;
  // Short tokens (e.g. "ai") must be whole-word — avoids "entertainment", "daily", etc.
  if (n.length <= 4) {
    const escaped = n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return new RegExp(`\\b${escaped}\\b`, 'i').test(haystack);
  }
  return haystack.includes(n);
}
function _collectText(metadata = {}) {
  const parts = [
    metadata.title,
    metadata.description,
    metadata.caption,
    ...(metadata.tags || []),
  ].filter(Boolean);
  return parts.join(' ').toLowerCase();
}

function _clipTitles(jobSpec = {}) {
  const items = jobSpec.order?.inputs?.items || jobSpec.items || [];
  return items
    .map((it) => it.title || it.headline || it.clipTitle || it.displayName || '')
    .filter(Boolean);
}

function _isShortForm(jobSpec = {}) {
  const ct = String(jobSpec.contentType || '').toLowerCase();
  const form = String(jobSpec.formType || jobSpec.order?.inputs?.formType || '').toLowerCase();
  return form === 'short' || ct.includes('short');
}

/** YouTube description SEO — applies to Shorts and long-form VOD. */
function validateYoutubeDescriptionSeo(description, { isShort } = {}) {
  const violations = [];
  const desc = String(description || '').trim();
  if (!desc) {
    violations.push('YouTube description is required');
    return violations;
  }

  const words = countWords(desc);
  const hashInDesc = countHashtagsInText(desc);
  const firstLine = desc.split('\n')[0] || '';

  if (firstLine.length < 40) {
    violations.push('description hook (first line) too short for YouTube SEO');
  }

  if (isShort) {
    if (words < 125) violations.push(`YouTube Shorts description too short (${words} words, need 125-250)`);
    if (words > 280) violations.push(`YouTube Shorts description too long (${words} words, max ~250)`);
  } else if (words < 125) {
    violations.push(`YouTube description too short (${words} words, aim 125-250+)`);
  }

  if (hashInDesc < 3) {
    violations.push(`description needs 3-5 hashtags inline (found ${hashInDesc})`);
  } else if (hashInDesc > 15) {
    violations.push(`description has too many hashtags (${hashInDesc}; YouTube ignores above 15)`);
  }

  if (!/subscribe/i.test(desc)) {
    violations.push('description missing Subscribe CTA');
  }

  return violations;
}

/**
 * Validate publish metadata against job content.
 * @returns {{ passed: boolean, violations: string[] }}
 */
function validatePublishMetadata(jobSpec = {}, metadata = {}) {
  const violations = [];
  const title = String(metadata.title || '').trim();
  const description = String(metadata.description || metadata.caption || '').trim();
  const prohibited = [
    ...DEFAULT_PROHIBITED,
    ...(jobSpec.designSpec?.voice?.prohibitedWords || []),
  ].map((w) => String(w).toLowerCase()).filter(Boolean);

  if (!title) violations.push('title is required');

  const haystack = _collectText({ ...metadata, title, description });
  for (const word of prohibited) {
    const needle = word.trim();
    if (!needle) continue;
    if (_hasProhibitedTerm(haystack, needle)) {
      violations.push(`prohibited term in metadata: "${needle.trim()}"`);
    }
  }

  const ct = String(jobSpec.contentType || '').toLowerCase();
  const isClipComp = ct.includes('short') || ct.includes('clip') || jobSpec.designSpec?.chrome?.layout === 'clip-comp';
  if (isClipComp && /\b(ai|artificial intelligence|chatgpt)\b/i.test(title)) {
    violations.push('clip comp title must not contain AI/ChatGPT marketing terms');
  }

  const clipTitles = _clipTitles(jobSpec);
  if (isClipComp && clipTitles.length > 0 && title) {
    const titleLower = title.toLowerCase();
    const anyMatch = clipTitles.some((t) => {
      const words = String(t).toLowerCase().split(/\s+/).filter((w) => w.length > 3);
      return words.some((w) => titleLower.includes(w));
    });
    if (!anyMatch) {
      violations.push('title does not reference any selected clip topic');
    }
  }

  // YouTube description SEO (Shorts + VOD) when description is present
  if (description) {
    violations.push(...validateYoutubeDescriptionSeo(description, { isShort: _isShortForm(jobSpec) }));
  }

  return { passed: violations.length === 0, violations };
}

function reviewHoldEnabled() {
  return String(process.env.C0_REVIEW_HOLD ?? 'on').toLowerCase() !== 'off';
}

module.exports = {
  validatePublishMetadata,
  validateYoutubeDescriptionSeo,
  reviewHoldEnabled,
  DEFAULT_PROHIBITED,
  countWords,
  countHashtagsInText,
};
